# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Light Home
email: knotlabs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Your Ultimate Home Lighting Source"
  When you move in to a home, you care about the furniture,
  the pictures on the wall, and the carpet on the floor. But
  what about lighting? Lighting is incredibly important to set
  the mood in any room, and for a place that you will be spending
  all of your time, why not make it amazing?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lighthome.co" # the base hostname & protocol for your site
permalink: /:categories/:title
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
